name: pgmoneta
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  highlighter: rouge
###
copyright: © 2022 <a href="https://www.redhat.com">Red Hat</a>
about: <a href="https://pgmoneta.github.io/">Backup / restore solution</a> for <a href="https://www.postgresql.org">PostgreSQL</a>
root: https://pgmoneta.github.io/
headers:
    - name: Configuration
      url: https://pgmoneta.github.io/configuration.html
    - name: Metrics
      url: https://pgmoneta.github.io/metrics.html
    - name: News
      url: https://pgmoneta.github.io/news.html
    - name: About
      url: https://pgmoneta.github.io/about.html
urls:
    - text: home
      url: https://pgmoneta.github.io
      icon: https://pgmoneta.github.io/images/icomoon/001-home.png
    - text: releases
      url: https://pgmoneta.github.io/releases.html
      icon: https://pgmoneta.github.io/images/icomoon/097-download.png
    - text: getting started
      url: https://pgmoneta.github.io/gettingstarted.html
      icon: https://pgmoneta.github.io/images/icomoon/027-bullhorn.png
    - text: tutorials
      url: https://pgmoneta.github.io/documentation.html
      icon: https://pgmoneta.github.io/images/icomoon/032-book.png

github:
    - text: github
      url: https://github.com/pgmoneta/pgmoneta
      icon: https://pgmoneta.github.io/images/icomoon/433-github.png
    - text: discussions
      url: https://github.com/pgmoneta/pgmoneta/discussions
      icon: https://pgmoneta.github.io/images/icomoon/115-users.png
    - text: issues
      url: https://github.com/pgmoneta/pgmoneta/issues
      icon: https://pgmoneta.github.io/images/icomoon/154-bug.png
    - text: license
      url: https://opensource.org/licenses/BSD-3-Clause
      icon: https://pgmoneta.github.io/images/icomoon/034-library.png
    - text: pgmoneta
      url: https://twitter.com/pgmoneta
      icon: https://pgmoneta.github.io/images/icomoon/407-twitter.png
